[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\waveform data logger'

[projects.cd]
path = 'Source\Waveform Data Logger Custom Device Project.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
name = 'waveform-data-logger-custom-device-{version}'
release_version = '1.0'
install_destination = 'documents\National Instruments\NI VeriStand {version}'
